//
//  ViewController.swift
//  FunTracker
//
//  Created by aumitche on 2015–10–02.
//  Copyright © 2015 NIMF. All rights reserved.
//

import UIKit

class ViewController: UIViewController {
    
    var closestBeaconID:String!
    var heartBeat:Double!
    @IBOutlet var slider:UISlider!
    
	override func viewDidLoad() {
		super.viewDidLoad()
		// Do any additional setup after loading the view, typically from a nib.
        
        var updateUserDataTimer = NSTimer.scheduledTimerWithTimeInterval(1, target: self, selector: Selector("updateUserData"), userInfo: nil, repeats: true);
	}

	override func didReceiveMemoryWarning() {
		super.didReceiveMemoryWarning()
		// Dispose of any resources that can be recreated.
	}
    
    func locateClosestBeacon() {
        print("Closest beacon identified: \(closestBeaconID)");
    }
    
    @IBAction func heartBeatChanged(sender: UISlider) {
        heartBeat = Double(sender.value)
    }
    
    func getHeartBeat() {
        print("Heartbeat Identified: \(heartBeat)");
        
        //Doesn't do anything right now, since the heartbeat is just generated by the slider for now
    }
    func updateUserData() {
        locateClosestBeacon();
        getHeartBeat();
        sendDataToServer();
        print("Data update complete!\n\n");
    }
    
    func sendDataToServer() {
        print("Data sent to server!");
    }
}

